### ISSUE TITLE
Unsupported option listed in javadoc

### ISSUE THREAD

**Issue by mohideen** [antlr/stringtemplate4#192] opened 2017-09-19 14:57 UTC
https://github.com/antlr/stringtemplate4/blob/f6d8a529e00f3dd79c7ea459a685775b84621989/src/org/stringtemplate/v4/ST.java#L566

The ST.format javadoc suggests that it supports named parameter rendering `ST.format("<name>:<phone>", "name", x, "phone", y);` while the implementation only supports number based arguments.

**Comment by sharwell** [comment] 2017-09-19 15:05
Thanks for the report!

This one is a duplicate of #113.

**Closed by sharwell** 2017-09-19 15:05 UTC
